version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    assignees:
      - "allen-mckenzie"
    commit-message:
      prefix: "Composer:"
      include: "scope"
    labels:
      - "Composer"
      - "Dependencies"
    reviewers:
      - "allen-mckenzie"
    target-branch: "main"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    assignees:
      - "allen-mckenzie"
    commit-message:
      prefix: "Node:"
      include: "scope"
    labels:
      - "JavaScript"
      - "Dependencies"
    reviewers:
      - "allen-mckenzie"
    target-branch: "main"
